# Bundles capture.json (real PyTorch output) into ../capture-data.js for the page.
#   python3 data/make-page-data.py
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(HERE, "capture.json")))
open(os.path.join(HERE, "..", "capture-data.js"), "w").write("/* generated by data/make-page-data.py from capture.json; do not edit */\nwindow.AUTOGRAD_CAPTURE = " + json.dumps(d) + ";\n")
print("wrote capture-data.js")
